'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Find the sum of all the even-valued terms in the sequence which do not exceed four million.
'''

x = 1
#print x
y = 2
#print y
sum = 2
while (x<=4000000)and(y<=4000000):
    x = x + y
    #print x
    if (x % 2==0)and(x<=4000000):
        sum = sum + x
    y = x + y
    #print y
    if (y % 2==0)and(y<=4000000):
        sum = sum + y
print sum
